server:
  addr: "0.0.0.0:9090"
  read_timeout: "60s"
  write_timeout: "60s"
  idle_timeout: "120s"

monitor:
  interval: "2s"
  collectors:
    proc:
      enable: true
      collect_per_core: false
      load_sample_cycle: "1s"
    sys:
      enable: true
      ignore_disks: ["/dev/sda", "/dev/sdb"]
      ignore_networks: ["lo", "docker0"]
    cgroup:
      enable: true
    container_runtime:
      enable: false

log:
  level: "debug"
  format: "json"
  path: "./app_logs"
  max_size: 200
  max_backup: 50
  max_age: 14
  compress: true